name: Daily Menu Bot

on:
  schedule:
    # Runs at 00:00 UTC every weekday (Mon-Fri)
    # 00:00 UTC = 09:00 KST (UTC+9)
    - cron: "0 0 * * 1-5"

  # Allow manual trigger for testing
  workflow_dispatch:

jobs:
  send-menu:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Seoul

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Run bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: npm start
